### ISSUE TITLE
请问这个支持解码tls中请求和响应数据吗

### ISSUE THREAD

**Issue by wang229819838** [lizongying/go-mitm#1]
之前都是burp工具做mitm，我想找一个golang语言开发的工具，burp工具太重了。

**Comment by lizongying** [comment]
> 之前都是burp工具做mitm，我想找一个golang语言开发的工具，burp工具太重了。

支持https（在个人认识里，一般认为tls是ssl的升级，通常SSL/TLS 表示的意思相同）。暂不支持websocket和非http协议。
